# Generated by Django 4.2.7 on 2024-01-06 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResetPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(default=False, max_length=250)),
            ],
        ),
    ]
