# Generated by Django 4.2.7 on 2024-01-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPasswordReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(default=False, max_length=350)),
            ],
        ),
        migrations.DeleteModel(
            name='ResetPass',
        ),
    ]
